### ISSUE TITLE
Unable to use commands or VS Code extension after new release on MacOS

### ISSUE THREAD

**Issue by littensy** [JohnnyMorganz/luau-lsp#566]
The latest extension version (1.28.0) displays the error `Luau Language Server client: couldn't create connection to server` when first opening a Luau file. This is not an issue for me with older versions of the extension.

### Output

```
[Error - 5:23:04 PM] Luau Language Server client: couldn't create connection to server.
Error: spawn Unknown system error -8
	at ChildProcess.spawn (node:internal/child_process:413:11)
	at Object.spawn (node:child_process:795:9)
	at /Users/richerd/.vscode/extensions/johnnymorganz.luau-lsp-1.28.0-darwin-arm64/dist/extension.js:2:484486
	at async w.createConnection (/Users/richerd/.vscode/extensions/johnnymorganz.luau-lsp-1.28.0-darwin-arm64/dist/extension.js:2:321350)
	at async w.start (/Users/richerd/.vscode/extensions/johnnymorganz.luau-lsp-1.28.0-darwin-arm64/dist/extension.js:2:311865)
	at async P (/Users/richerd/.vscode/extensions/johnnymorganz.luau-lsp-1.28.0-darwin-arm64/dist/extension.js:2:237705)
	at async t.activate (/Users/richerd/.vscode/extensions/johnnymorganz.luau-lsp-1.28.0-darwin-arm64/dist/extension.js:2:239409)
	at async u.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:6255)
	at async u.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:6218)
	at async u.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:5675)
```

### Details

**Chip:** Apple M1 Pro
**MacOS:** Sonoma 14.4 Beta
**VS Code:** 1.87

**Comment by littensy** [comment]
Using `luau-lsp` via the command line also causes this error:
```sh
/Users/richerd/.aftman/tool-storage/johnnymorganz/luau-lsp/1.28.0/luau-lsp: /Users/richerd/.aftman/tool-storage/johnnymorganz/luau-lsp/1.28.0/luau-lsp: cannot execute binary file
```

**Comment by helgoboss** [comment]
Happens here, too. M1 Air.

**Comment by JohnnyMorganz** [comment]
Apologies, I accidently broke the macos release pipeline by unintentionally switching it to a ubuntu runner. Will release 1.28.1

**Comment by JohnnyMorganz** [comment]
Released: https://github.com/JohnnyMorganz/luau-lsp/releases/tag/1.28.1 - sorry for inconvenience!

**Comment by helgoboss** [comment]
Thank you so much for the quick fix. Now it works. This release is awesome. Great to see property autocompletion within table literals without having to type first!
