### ISSUE TITLE
Luau Language Server client: couldn't create connection to server

### ISSUE THREAD

**Issue by Pymon02** [JohnnyMorganz/luau-lsp#696]
```
[Error - 8:50:31 AM] Luau Language Server client: couldn't create connection to server.
Error: spawn EPERM
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:799:9)
	at c:\Users\jacob\.vscode\extensions\johnnymorganz.luau-lsp-1.32.0-win32-x64\dist\extension.js:2:878762
	at async B.createConnection (c:\Users\jacob\.vscode\extensions\johnnymorganz.luau-lsp-1.32.0-win32-x64\dist\extension.js:2:715580)
	at async B.start (c:\Users\jacob\.vscode\extensions\johnnymorganz.luau-lsp-1.32.0-win32-x64\dist\extension.js:2:706095)
	at async f (c:\Users\jacob\.vscode\extensions\johnnymorganz.luau-lsp-1.32.0-win32-x64\dist\extension.js:2:234910)
	at async t.activate (c:\Users\jacob\.vscode\extensions\johnnymorganz.luau-lsp-1.32.0-win32-x64\dist\extension.js:2:232266)
	at async c.n (c:\Users\jacob\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6384)
	at async c.m (c:\Users\jacob\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6347)
	at async c.l (c:\Users\jacob\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:5804)```

**Comment by Pymon02** [comment]
Only happens with `v1.32.0` Does not happen with `v1.31.1`

**Comment by JohnnyMorganz** [comment]
Does this consistently occur for you? And do you have any repro steps?

Also are you on windows, and do you have the MSVC runtime already installed?
